
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jay/.local/share/JetBrains/Toolbox/apps/clion-nova/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.6-76060606-generic - x86_64
...
